library(tidyr)
hpcdata <- read.table("household_power_consumption.txt", header=TRUE, nrows=70000, sep=";",comment.char = "",na.strings="?")
hpcsubdata <- subset(hpcdata, Date =="1/2/2007"|Date=="2/2/2007")
hpcdatetime <- unite(hpcsubdata, datetime, c(Date, Time), sep = " ")
hpcdatetime$datetime <- strptime(hpcdatetime$datetime, format = "%d/%m/%Y %H:%M:%S")
png(filename="plot4.png")
par(mfcol = c(2,2))
with(hpcdatetime, plot(datetime, Global_active_power, type = "l",xlab= "",ylab= "Global Active Power(kilowatts)"))
with(hpcdatetime, plot(datetime, Sub_metering_1, type = "l",xlab="", ylab= "Energy sub metering"))
lines(hpcdatetime$datetime,hpcdatetime$Sub_metering_2,col="red")
lines(hpcdatetime$datetime,hpcdatetime$Sub_metering_3,col="blue")
legend("topright",bty="n",col = c("black","red","blue"),lty=1,legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
with(hpcdatetime, plot(datetime, Voltage, type = "l",ylab= "Voltage"))
with(hpcdatetime, plot(datetime, Global_reactive_power, type = "l",ylab= "Global_reactive_power"))
dev.off()