library(tidyr)
hpcdata <- read.table("household_power_consumption.txt", header=TRUE, nrows=70000, sep=";",comment.char = "",na.strings="?")
hpcsubdata <- subset(hpcdata, Date =="1/2/2007"|Date=="2/2/2007")
hpcdatetime <- unite(hpcsubdata, datetime, c(Date, Time), sep = " ")
hpcdatetime$datetime <- strptime(hpcdatetime$datetime, format = "%d/%m/%Y %H:%M:%S")
png(filename="plot3.png")
with(hpcdatetime, plot(datetime, Sub_metering_1, type = "l",xlab="", ylab= "Energy sub metering"))
lines(hpcdatetime$datetime,hpcdatetime$Sub_metering_2,col="red")
lines(hpcdatetime$datetime,hpcdatetime$Sub_metering_3,col="blue")
legend("topright", col = c("black","red","blue"),lty=1,legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()